apiVersion: v1
data:
  # 下面的 client-id、client-secret 可以向 oauth 服务提供者拿到
  client-id: bb9812db6828b853cec9
  client-secret: 8ca568df2709c9a662bc85b2ec3e6e42cea75382
kind: Secret
metadata:
  name: argo-workflows-sso
